version: '3.7'
services:
  resources:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    container_name: resources
    command: bash
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
networks:
  default:
    name: daphne-network
    external: true
