version: '3.7'
services:
  resources:
    image: python:3.8-slim-buster
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    container_name: resources
networks:
  default:
    name: daphne-network
    external: true
